vrrp_script chk_haproxy {
  script "/usr/bin/killall -0 haproxy"
  interval 2
  weight 2
  fall 3
  rise 2
}

vrrp_instance VI_1 {
  state ___KEEPALIVED_STATE___
  interface ___ETH_PRIMARY_INTERFACE___
  virtual_router_id ___KEEPALIVED_VIRTUAL_ROUTER_ID___
  priority ___KEEPALIVED_PRIORITY___
  advert_int 1
  smtp_alert

  authentication {
    auth_type PASS
    auth_pass ___KEEPALIVED_PASSWORD___
  }

  unicast_src_ip ___ETH_PRIMARY_IP___
  unicast_peer {
    ___KEEPALIVED_PEER_IP___
  }

  virtual_ipaddress {
    ___KEEPALIVED_VIRTUAL_IP___ dev ___ETH_PRIMARY_INTERFACE___
  }

  track_script {
    chk_haproxy
  }

  notify_master "/etc/keepalived/notify.sh MASTER"
  notify_backup "/etc/keepalived/notify.sh BACKUP"
  notify_fault  "/etc/keepalived/notify.sh FAULT"
}
